
INSERT INTO "songs" VALUES (1,'In the End','kkkkk','llll');
INSERT INTO "songs" VALUES (2,'Numb','kkkkk','llll');
INSERT INTO "songs" VALUES (3,'Crawling','kkkkk','llll');
INSERT INTO "songs" VALUES (4,'One Step Closer','kkkkk','llll');
INSERT INTO "songs" VALUES (5,'Breaking the Habit','kkkkk','llll');
INSERT INTO "songs" VALUES (6,'Faint','kkkkk','llll');
INSERT INTO "songs" VALUES (7,'Bleed It Out','kkkkk','llll');
INSERT INTO "songs" VALUES (8,'What I''ve Done','kkkkk','llll');
INSERT INTO "songs" VALUES (9,'Mediterranean Nights','kkkkk','llll');
INSERT INTO "songs" VALUES (10,'Santorini Sunset','kkkkk','llll');
INSERT INTO "songs" VALUES (11,'Olive Grove Dance','kkkkk','llll');
INSERT INTO "songs" VALUES (12,'Zorba''s Fire','kkkkk','llll');
INSERT INTO "songs" VALUES (13,'Mykonos Breeze','kkkkk','llll');
INSERT INTO "songs" VALUES (14,'Athens by Moonlight','kkkkk','llll');
INSERT INTO "songs" VALUES (15,'Dusty Roads','kkkkk','llll');
INSERT INTO "songs" VALUES (16,'Whiskey River','kkkkk','llll');
INSERT INTO "songs" VALUES (17,'Pickup Truck Blues','kkkkk','llll');
INSERT INTO "songs" VALUES (18,'Honky Tonk Heaven','kkkkk','llll');
INSERT INTO "songs" VALUES (19,'Cowboy''s Lament','kkkkk','llll');
INSERT INTO "songs" VALUES (20,'Heartbreak Highway','kkkkk','llll');
INSERT INTO "songs" VALUES (21,'Bluegrass Memories','kkkkk','llll');
INSERT INTO "songs" VALUES (22,'Smoky Mountain Rain','kkkkk','llll');
INSERT INTO "songs" VALUES (23,'Banjo Breakdown','kkkkk','llll');
INSERT INTO "songs" VALUES (24,'Parisian Nights','kkkkk','llll');
INSERT INTO "songs" VALUES (25,'Cafe au Lait','kkkkk','llll');
INSERT INTO "songs" VALUES (26,'Seine Serenade','kkkkk','llll');
INSERT INTO "songs" VALUES (27,'Eiffel Tower Dreams','kkkkk','llll');
INSERT INTO "songs" VALUES (28,'Champs-Élysées Stroll','kkkkk','llll');
INSERT INTO "songs" VALUES (29,'Louvre''s Mystery','kkkkk','llll');
INSERT INTO "songs" VALUES (30,'Notre-Dame Bells','kkkkk','llll');
INSERT INTO "songs" VALUES (31,'Crystal Waters','kkkkk','llll');
INSERT INTO "songs" VALUES (32,'Midnight Whispers','kkkkk','llll');
INSERT INTO "songs" VALUES (33,'Starlight Sonata','kkkkk','llll');
INSERT INTO "songs" VALUES (34,'Ethereal Dreams','kkkkk','llll');
INSERT INTO "songs" VALUES (35,'Angel''s Lullaby','kkkkk','llll');
INSERT INTO "songs" VALUES (36,'Mystic Forest','kkkkk','llll');
INSERT INTO "songs" VALUES (37,'Fairy Dance','kkkkk','llll');
INSERT INTO "songs" VALUES (38,'Rainbow''s End','kkkkk','llll');
INSERT INTO "songs" VALUES (39,'Lone Star Nights','kkkkk','llll');
INSERT INTO "songs" VALUES (40,'Rodeo Romance','kkkkk','llll');
INSERT INTO "songs" VALUES (41,'Alamo Sunset','kkkkk','llll');
INSERT INTO "songs" VALUES (42,'Gulf Coast Blues','kkkkk','llll');
INSERT INTO "songs" VALUES (43,'Hill Country Rain','kkkkk','llll');
INSERT INTO "songs" VALUES (44,'Big D Lights','kkkkk','llll');
INSERT INTO "songs" VALUES (45,'Yellow Rose','kkkkk','llll');
INSERT INTO "songs" VALUES (46,'Panhandle Wind','kkkkk','llll');
INSERT INTO "songs" VALUES (47,'Rio Grande Rhythm','kkkkk','llll');
INSERT INTO "songs" VALUES (48,'Ocean Breeze','kkkkk','llll');
INSERT INTO "songs" VALUES (49,'Seashell Whispers','kkkkk','llll');
INSERT INTO "songs" VALUES (50,'Sandcastle Dreams','kkkkk','llll');
INSERT INTO "songs" VALUES (51,'Sunset Serenade','kkkkk','llll');
INSERT INTO "songs" VALUES (52,'Dolphin Dance','kkkkk','llll');
INSERT INTO "songs" VALUES (53,'Tropical Storm','kkkkk','llll');
INSERT INTO "songs" VALUES (54,'Coral Reef Symphony','kkkkk','llll');
INSERT INTO "songs" VALUES (55,'Mermaid''s Song','kkkkk','llll');
INSERT INTO "songs" VALUES (56,'Tidal Pool Reflections','kkkkk','llll');
INSERT INTO "songs" VALUES (57,'Jellyfish Waltz','kkkkk','llll');
INSERT INTO "songs" VALUES (58,'Seahorse Lullaby','kkkkk','llll');
INSERT INTO "songs" VALUES (59,'Kelp Forest Whispers','kkkkk','llll');
INSERT INTO "songs" VALUES (60,'Octopus Garden','kkkkk','llll');
INSERT INTO "songs" VALUES (61,'Shipwreck Secrets','kkkkk','llll');
INSERT INTO "songs" VALUES (62,'Flamenco Fire','kkkkk','llll');
INSERT INTO "songs" VALUES (63,'Gypsy Caravan','kkkkk','llll');
INSERT INTO "songs" VALUES (64,'Tango for Two','kkkkk','llll');
INSERT INTO "songs" VALUES (65,'Salsa Nights','kkkkk','llll');
INSERT INTO "songs" VALUES (66,'Samba Sunrise','kkkkk','llll');
INSERT INTO "songs" VALUES (67,'Bossa Nova Breeze','kkkkk','llll');
INSERT INTO "songs" VALUES (68,'Rumba Romance','kkkkk','llll');
INSERT INTO "songs" VALUES (69,'Celtic Twilight','kkkkk','llll');
INSERT INTO "songs" VALUES (70,'Druid''s Dance','kkkkk','llll');
INSERT INTO "songs" VALUES (71,'Fairy Ring','kkkkk','llll');
INSERT INTO "songs" VALUES (72,'Highlands Pipe','kkkkk','llll');
INSERT INTO "songs" VALUES (73,'Selkie''s Song','kkkkk','llll');
INSERT INTO "songs" VALUES (74,'Beltane Fire','kkkkk','llll');
INSERT INTO "songs" VALUES (75,'Avalon''s Dream','kkkkk','llll');
INSERT INTO "songs" VALUES (76,'Wishing Well','kkkkk','llll');
INSERT INTO "songs" VALUES (77,'Leprechaun''s Jig','kkkkk','llll');
INSERT INTO "songs" VALUES (78,'Desert Wind','kkkkk','llll');
INSERT INTO "songs" VALUES (79,'Oasis Dreams','kkkkk','llll');
INSERT INTO "songs" VALUES (80,'Camel Caravan','kkkkk','llll');
INSERT INTO "songs" VALUES (81,'Mirage Melody','kkkkk','llll');
INSERT INTO "songs" VALUES (82,'Bedouin Camp','kkkkk','llll');
INSERT INTO "songs" VALUES (83,'Sandstorm','kkkkk','llll');
INSERT INTO "songs" VALUES (84,'Pyramid''s Secret','kkkkk','llll');
INSERT INTO "songs" VALUES (85,'Mermaid''s Lament','kkkkk','llll');
INSERT INTO "songs" VALUES (86,'Coral Castle','kkkkk','llll');
INSERT INTO "songs" VALUES (87,'Siren''s Call','kkkkk','llll');
INSERT INTO "songs" VALUES (88,'Triton''s Trumpet','kkkkk','llll');
INSERT INTO "songs" VALUES (89,'Sea Witch''s Spell','kkkkk','llll');
INSERT INTO "songs" VALUES (90,'Sailor''s Delight','kkkkk','llll');
INSERT INTO "songs" VALUES (91,'Pearl Diving','kkkkk','llll');
INSERT INTO "songs" VALUES (92,'Neon Nights','kkkkk','llll');
INSERT INTO "songs" VALUES (93,'Midnight Drive','kkkkk','llll');
INSERT INTO "songs" VALUES (94,'Jukebox Hero','kkkkk','llll');
INSERT INTO "songs" VALUES (95,'Backstage Pass','kkkkk','llll');
INSERT INTO "songs" VALUES (96,'Guitar Solo','kkkkk','llll');
INSERT INTO "songs" VALUES (97,'Leather and Lace','kkkkk','llll');
INSERT INTO "songs" VALUES (98,'Stadium Rocker','kkkkk','llll');
INSERT INTO "songs" VALUES (99,'Fresh Start','kkkkk','llll');
INSERT INTO "songs" VALUES (100,'First Steps','kkkkk','llll');
INSERT INTO "songs" VALUES (101,'Blank Canvas','kkkkk','llll');
INSERT INTO "songs" VALUES (102,'Untitled','kkkkk','llll');
INSERT INTO "songs" VALUES (103,'Origin Story','kkkkk','llll');
INSERT INTO "songs" VALUES (104,'Debut','kkkkk','llll');
INSERT INTO "users" VALUES (1,'saran','saran@gmail.com','12345','commom');
INSERT INTO "users" VALUES (2,'linkinpark','lp@song.com','12345','artist');
INSERT INTO "users" VALUES (3,'Yorgo','ygridley0@dagondesign.com','56','artist');
INSERT INTO "users" VALUES (4,'Tedra','tdiegan1@i2i.jp','43','commoner');
INSERT INTO "users" VALUES (5,'Zeke','ztheyer2@istockphoto.com','7593','artist');
INSERT INTO "users" VALUES (6,'Bastien','bandrioni3@acquirethisname.com','307','artist');
INSERT INTO "users" VALUES (7,'Peirce','pkitchen4@buzzfeed.com','20807','commoner');
INSERT INTO "users" VALUES (8,'Chryste','cdykas5@so-net.ne.jp','1','artist');
INSERT INTO "users" VALUES (9,'Dallas','dlebretondelavieuville6@so-net.ne.jp','16248','artist');
INSERT INTO "users" VALUES (10,'Janeen','jreignould7@elegantthemes.com','3','commoner');
INSERT INTO "users" VALUES (11,'Lurette','lwetherburn8@tumblr.com','240','commoner');
INSERT INTO "users" VALUES (12,'Julian','jbeglin9@theglobeandmail.com','2862','commoner');
INSERT INTO "users" VALUES (13,'Salome','struswella@people.com.cn','103','commoner');
INSERT INTO "users" VALUES (14,'Shellie','scranfieldb@sun.com','87847','artist');
INSERT INTO "users" VALUES (15,'Bobbie','bchapec@tumblr.com','871','commoner');
INSERT INTO "users" VALUES (16,'Halimeda','hpaoluccid@homestead.com','3802','artist');
INSERT INTO "users" VALUES (17,'Magnum','mtixiere@prnewswire.com','75954','commoner');
INSERT INTO "users" VALUES (18,'Rossy','rkeanef@people.com.cn','5931','artist');
INSERT INTO "users" VALUES (19,'Olwen','osimakovg@bravesites.com','39','artist');
INSERT INTO "users" VALUES (20,'Udall','uhammanth@usgs.gov','2747','artist');
INSERT INTO "users" VALUES (21,'Ariel','aondrusi@youku.com','85','artist');
INSERT INTO "users" VALUES (22,'Darrell','drubesj@pagesperso-orange.fr','7','artist');
INSERT INTO "users" VALUES (23,'newuser','newusr@eml.com','123456789','artist');
INSERT INTO "users" VALUES (24,'user2','newusr2@eml.com','1234','commom');
INSERT INTO "users" VALUES (25,'user4','usr4@eml.com','1234','commoner');
INSERT INTO "users" VALUES (26,'kwqefjkwq','segk.mwrk@eml.com','12345','commoner');
INSERT INTO "albums" VALUES (1,'Hybrid Theory','1,3,4');
INSERT INTO "albums" VALUES (2,'Meteora','2,5,6');
INSERT INTO "albums" VALUES (3,'Minutes to Midnight','7,8');
INSERT INTO "albums" VALUES (4,'Aegean Dreams','9,10,11,12');
INSERT INTO "albums" VALUES (5,'Island Melodies','13,14,16');
INSERT INTO "albums" VALUES (6,'Backwoods Tales','15,17,19,20');
INSERT INTO "albums" VALUES (7,'Neon Nights','18');
INSERT INTO "albums" VALUES (8,'Mountain Home','21,22,23,26,24');
INSERT INTO "albums" VALUES (9,'Morning in Montmartre','25');
INSERT INTO "albums" VALUES (10,'River Romance','26');
INSERT INTO "albums" VALUES (11,'Steel and Stone','27');
INSERT INTO "albums" VALUES (12,'Boulevard Beats','28');
INSERT INTO "albums" VALUES (13,'Art and Soul','29');
INSERT INTO "albums" VALUES (14,'Gothic Echoes','30');
INSERT INTO "albums" VALUES (15,'Sapphire Seas','31');
INSERT INTO "albums" VALUES (16,'Velvet Moon','32');
INSERT INTO "albums" VALUES (17,'Cosmic Symphony','33');
INSERT INTO "albums" VALUES (18,'Celestial Journey','34');
INSERT INTO "albums" VALUES (19,'Heavenly Harmonies','35');
INSERT INTO "albums" VALUES (20,'Enchanted Woods','36');
INSERT INTO "albums" VALUES (21,'Whimsical Wonders','37');
INSERT INTO "albums" VALUES (22,'Prism of Hope','38');
INSERT INTO "albums" VALUES (23,'Texas Skies','39');
INSERT INTO "albums" VALUES (24,'Bucking Broncos','40');
INSERT INTO "albums" VALUES (25,'Remember When','41');
INSERT INTO "albums" VALUES (26,'Saltwater Dreams','42');
INSERT INTO "albums" VALUES (27,'Natural State','43');
INSERT INTO "albums" VALUES (28,'City Slicker','44');
INSERT INTO "albums" VALUES (29,'Bluebonnet Fields','45');
INSERT INTO "albums" VALUES (30,'Wide Open Spaces','46');
INSERT INTO "albums" VALUES (31,'Border Town Beat','47');
INSERT INTO "albums" VALUES (32,'Coastal Serenity','48');
INSERT INTO "albums" VALUES (33,'Tidal Treasures','49');
INSERT INTO "albums" VALUES (34,'Beach Memories','50');
INSERT INTO "albums" VALUES (35,'Golden Hour','51');
INSERT INTO "albums" VALUES (36,'Marine Melodies','52');
INSERT INTO "albums" VALUES (37,'Island Intensity','53');
INSERT INTO "albums" VALUES (38,'Underwater Wonders','54');
INSERT INTO "albums" VALUES (39,'Mythical Seas','55');
INSERT INTO "albums" VALUES (40,'Coastal Contemplations','56');
INSERT INTO "albums" VALUES (41,'Bioluminescent Ballet','57');
INSERT INTO "albums" VALUES (42,'Aquarium Dreams','58');
INSERT INTO "albums" VALUES (43,'Green Depths','59');
INSERT INTO "albums" VALUES (44,'Tentacle Tango','60');
INSERT INTO "albums" VALUES (45,'Sunken Treasures','61');
INSERT INTO "albums" VALUES (46,'Spanish Passion','62');
INSERT INTO "albums" VALUES (47,'Wanderlust','63');
INSERT INTO "albums" VALUES (48,'Midnight in Buenos Aires','64');
INSERT INTO "albums" VALUES (49,'Caribbean Heat','65');
INSERT INTO "albums" VALUES (50,'Rio Rhythms','66');
INSERT INTO "albums" VALUES (51,'Ipanema Dreams','67');
INSERT INTO "albums" VALUES (52,'Havana Nights','68');
INSERT INTO "albums" VALUES (53,'Emerald Mists','69');
INSERT INTO "albums" VALUES (54,'Ancient Stones','70');
INSERT INTO "albums" VALUES (55,'Enchanted Forest','71');
INSERT INTO "albums" VALUES (56,'Misty Mountains','72');
INSERT INTO "albums" VALUES (57,'Ocean''s Call','73');
INSERT INTO "albums" VALUES (58,'Wheel of the Year','74');
INSERT INTO "albums" VALUES (59,'Mystic Isle','75');
INSERT INTO "albums" VALUES (60,'Folklore and Fantasy','76');
INSERT INTO "albums" VALUES (61,'Green Magic','77');
INSERT INTO "albums" VALUES (62,'Sahara Nights','78');
INSERT INTO "albums" VALUES (63,'Palm and Sand','79');
INSERT INTO "albums" VALUES (64,'Silk Road Journey','80');
INSERT INTO "albums" VALUES (65,'Heat Haze','81');
INSERT INTO "albums" VALUES (66,'Nomad''s Tale','82');
INSERT INTO "albums" VALUES (67,'Nature''s Fury','83');
INSERT INTO "albums" VALUES (68,'Ancient Mystery','84');
INSERT INTO "albums" VALUES (69,'Under the Sea','85');
INSERT INTO "albums" VALUES (70,'Underwater Kingdom','86');
INSERT INTO "albums" VALUES (71,'Enchanted Waters','87');
INSERT INTO "albums" VALUES (72,'Ocean Depths','88');
INSERT INTO "albums" VALUES (73,'Dark Tides','89');
INSERT INTO "albums" VALUES (74,'Above the Waves','90');
INSERT INTO "albums" VALUES (75,'Hidden Treasures','91');
INSERT INTO "albums" VALUES (76,'City Lights','92');
INSERT INTO "albums" VALUES (77,'Open Road','93');
INSERT INTO "albums" VALUES (78,'Rock ''n'' Roll Dreams','94');
INSERT INTO "albums" VALUES (79,'Superstar','95');
INSERT INTO "albums" VALUES (80,'Six String Stories','96');
INSERT INTO "albums" VALUES (81,'Bad Boy Blues','97');
INSERT INTO "albums" VALUES (82,'Crowd Pleaser','98');
INSERT INTO "albums" VALUES (83,'Beginnings','99');
INSERT INTO "albums" VALUES (84,'New Horizons','100');
INSERT INTO "albums" VALUES (85,'Infinite Possibilities','101');
INSERT INTO "albums" VALUES (86,'Work in Progress','102');
INSERT INTO "albums" VALUES (87,'Chapter One','103');
INSERT INTO "albums" VALUES (88,'Breaking Through','104');
INSERT INTO "artist_album_relationship" VALUES (2,1);
INSERT INTO "artist_album_relationship" VALUES (2,2);
INSERT INTO "artist_album_relationship" VALUES (2,7);
INSERT INTO "artist_album_relationship" VALUES (3,9);
INSERT INTO "artist_album_relationship" VALUES (3,13);
INSERT INTO "artist_album_relationship" VALUES (5,15);
INSERT INTO "artist_album_relationship" VALUES (5,18);
INSERT INTO "artist_album_relationship" VALUES (5,21);
INSERT INTO "artist_album_relationship" VALUES (6,25);
INSERT INTO "artist_album_relationship" VALUES (6,26);
INSERT INTO "artist_album_relationship" VALUES (6,27);
INSERT INTO "artist_album_relationship" VALUES (6,28);
INSERT INTO "artist_album_relationship" VALUES (6,29);
INSERT INTO "artist_album_relationship" VALUES (6,30);
INSERT INTO "artist_album_relationship" VALUES (8,31);
INSERT INTO "artist_album_relationship" VALUES (8,32);
INSERT INTO "artist_album_relationship" VALUES (8,33);
INSERT INTO "artist_album_relationship" VALUES (8,34);
INSERT INTO "artist_album_relationship" VALUES (8,35);
INSERT INTO "artist_album_relationship" VALUES (8,36);
INSERT INTO "artist_album_relationship" VALUES (8,37);
INSERT INTO "artist_album_relationship" VALUES (8,38);
INSERT INTO "artist_album_relationship" VALUES (9,39);
INSERT INTO "artist_album_relationship" VALUES (9,40);
INSERT INTO "artist_album_relationship" VALUES (9,41);
INSERT INTO "artist_album_relationship" VALUES (9,42);
INSERT INTO "artist_album_relationship" VALUES (9,43);
INSERT INTO "artist_album_relationship" VALUES (9,44);
INSERT INTO "artist_album_relationship" VALUES (9,45);
INSERT INTO "artist_album_relationship" VALUES (9,46);
INSERT INTO "artist_album_relationship" VALUES (9,47);
INSERT INTO "artist_album_relationship" VALUES (14,48);
INSERT INTO "artist_album_relationship" VALUES (14,49);
INSERT INTO "artist_album_relationship" VALUES (14,50);
INSERT INTO "artist_album_relationship" VALUES (14,51);
INSERT INTO "artist_album_relationship" VALUES (14,52);
INSERT INTO "artist_album_relationship" VALUES (14,53);
INSERT INTO "artist_album_relationship" VALUES (16,54);
INSERT INTO "artist_album_relationship" VALUES (16,55);
INSERT INTO "artist_album_relationship" VALUES (16,56);
INSERT INTO "artist_album_relationship" VALUES (16,57);
INSERT INTO "artist_album_relationship" VALUES (16,58);
INSERT INTO "artist_album_relationship" VALUES (16,59);
INSERT INTO "artist_album_relationship" VALUES (16,60);
INSERT INTO "artist_album_relationship" VALUES (16,61);
INSERT INTO "artist_album_relationship" VALUES (18,62);
INSERT INTO "artist_album_relationship" VALUES (18,63);
INSERT INTO "artist_album_relationship" VALUES (18,64);
INSERT INTO "artist_album_relationship" VALUES (18,65);
INSERT INTO "artist_album_relationship" VALUES (18,66);
INSERT INTO "artist_album_relationship" VALUES (18,67);
INSERT INTO "artist_album_relationship" VALUES (18,68);
INSERT INTO "artist_album_relationship" VALUES (19,69);
INSERT INTO "artist_album_relationship" VALUES (19,70);
INSERT INTO "artist_album_relationship" VALUES (19,71);
INSERT INTO "artist_album_relationship" VALUES (19,72);
INSERT INTO "artist_album_relationship" VALUES (19,73);
INSERT INTO "artist_album_relationship" VALUES (19,74);
INSERT INTO "artist_album_relationship" VALUES (19,75);
INSERT INTO "artist_album_relationship" VALUES (19,76);
INSERT INTO "artist_album_relationship" VALUES (19,77);
INSERT INTO "artist_album_relationship" VALUES (20,78);
INSERT INTO "artist_album_relationship" VALUES (20,79);
INSERT INTO "artist_album_relationship" VALUES (20,80);
INSERT INTO "artist_album_relationship" VALUES (20,81);
INSERT INTO "artist_album_relationship" VALUES (20,82);
INSERT INTO "artist_album_relationship" VALUES (20,83);
INSERT INTO "artist_album_relationship" VALUES (20,84);
INSERT INTO "artist_album_relationship" VALUES (21,85);
INSERT INTO "artist_album_relationship" VALUES (21,86);
INSERT INTO "artist_album_relationship" VALUES (21,87);
INSERT INTO "artist_album_relationship" VALUES (21,88);
COMMIT;
