

songs 

INSERT INTO songs (name, mp_url, album_art) VALUES
( 'In the End', 'kkkkk', 'llll'),
( 'Numb', 'kkkkk', 'llll'),
( 'Crawling', 'kkkkk', 'llll'),
( 'One Step Closer', 'kkkkk', 'llll'),
( 'Breaking the Habit', 'kkkkk', 'llll'),
( 'Faint', 'kkkkk', 'llll'),
( 'Bleed It Out', 'kkkkk', 'llll'),
( 'What I''ve Done', 'kkkkk', 'llll'),
( 'Mediterranean Nights', 'kkkkk', 'llll'),
( 'Santorini Sunset', 'kkkkk', 'llll'),
( 'Olive Grove Dance', 'kkkkk', 'llll'),
( 'Zorba''s Fire', 'kkkkk', 'llll'),
( 'Mykonos Breeze', 'kkkkk', 'llll'),
( 'Athens by Moonlight', 'kkkkk', 'llll'),
( 'Dusty Roads', 'kkkkk', 'llll'),
( 'Whiskey River', 'kkkkk', 'llll'),
( 'Pickup Truck Blues', 'kkkkk', 'llll'),
( 'Honky Tonk Heaven', 'kkkkk', 'llll'),
( 'Cowboy''s Lament', 'kkkkk', 'llll'),
( 'Heartbreak Highway', 'kkkkk', 'llll'),
( 'Bluegrass Memories', 'kkkkk', 'llll'),
( 'Smoky Mountain Rain', 'kkkkk', 'llll'),
( 'Banjo Breakdown', 'kkkkk', 'llll'),
( 'Parisian Nights', 'kkkkk', 'llll'),
( 'Cafe au Lait', 'kkkkk', 'llll'),
( 'Seine Serenade', 'kkkkk', 'llll'),
( 'Eiffel Tower Dreams', 'kkkkk', 'llll'),
( 'Champs-Élysées Stroll', 'kkkkk', 'llll'),
( 'Louvre''s Mystery', 'kkkkk', 'llll'),
( 'Notre-Dame Bells', 'kkkkk', 'llll'),
( 'Crystal Waters', 'kkkkk', 'llll'),
( 'Midnight Whispers', 'kkkkk', 'llll'),
( 'Starlight Sonata', 'kkkkk', 'llll'),
( 'Ethereal Dreams', 'kkkkk', 'llll'),
( 'Angel''s Lullaby', 'kkkkk', 'llll'),
( 'Mystic Forest', 'kkkkk', 'llll'),
( 'Fairy Dance', 'kkkkk', 'llll'),
( 'Rainbow''s End', 'kkkkk', 'llll'),
( 'Lone Star Nights', 'kkkkk', 'llll'),
( 'Rodeo Romance', 'kkkkk', 'llll'),
( 'Alamo Sunset', 'kkkkk', 'llll'),
( 'Gulf Coast Blues', 'kkkkk', 'llll'),
( 'Hill Country Rain', 'kkkkk', 'llll'),
( 'Big D Lights', 'kkkkk', 'llll'),
( 'Yellow Rose', 'kkkkk', 'llll'),
( 'Panhandle Wind', 'kkkkk', 'llll'),
( 'Rio Grande Rhythm', 'kkkkk', 'llll'),
( 'Ocean Breeze', 'kkkkk', 'llll'),
( 'Seashell Whispers', 'kkkkk', 'llll'),
( 'Sandcastle Dreams', 'kkkkk', 'llll'),
( 'Sunset Serenade', 'kkkkk', 'llll'),
( 'Dolphin Dance', 'kkkkk', 'llll'),
( 'Tropical Storm', 'kkkkk', 'llll'),
( 'Coral Reef Symphony', 'kkkkk', 'llll'),
( 'Mermaid''s Song', 'kkkkk', 'llll'),
( 'Tidal Pool Reflections', 'kkkkk', 'llll'),
( 'Jellyfish Waltz', 'kkkkk', 'llll'),
( 'Seahorse Lullaby', 'kkkkk', 'llll'),
( 'Kelp Forest Whispers', 'kkkkk', 'llll'),
( 'Octopus Garden', 'kkkkk', 'llll'),
( 'Shipwreck Secrets', 'kkkkk', 'llll'),
( 'Flamenco Fire', 'kkkkk', 'llll'),
( 'Gypsy Caravan', 'kkkkk', 'llll'),
( 'Tango for Two', 'kkkkk', 'llll'),
( 'Salsa Nights', 'kkkkk', 'llll'),
( 'Samba Sunrise', 'kkkkk', 'llll'),
( 'Bossa Nova Breeze', 'kkkkk', 'llll'),
( 'Rumba Romance', 'kkkkk', 'llll'),
( 'Celtic Twilight', 'kkkkk', 'llll'),
( 'Druid''s Dance', 'kkkkk', 'llll'),
( 'Fairy Ring', 'kkkkk', 'llll'),
( 'Highlands Pipe', 'kkkkk', 'llll'),
( 'Selkie''s Song', 'kkkkk', 'llll'),
( 'Beltane Fire', 'kkkkk', 'llll'),
( 'Avalon''s Dream', 'kkkkk', 'llll'),
( 'Wishing Well', 'kkkkk', 'llll'),
( 'Leprechaun''s Jig', 'kkkkk', 'llll'),
( 'Desert Wind', 'kkkkk', 'llll'),
( 'Oasis Dreams', 'kkkkk', 'llll'),
( 'Camel Caravan', 'kkkkk', 'llll'),
( 'Mirage Melody', 'kkkkk', 'llll'),
( 'Bedouin Camp', 'kkkkk', 'llll'),
( 'Sandstorm', 'kkkkk', 'llll'),
( 'Pyramid''s Secret', 'kkkkk', 'llll'),
( 'Mermaid''s Lament', 'kkkkk', 'llll'),
( 'Coral Castle', 'kkkkk', 'llll'),
( 'Siren''s Call', 'kkkkk', 'llll'),
( 'Triton''s Trumpet', 'kkkkk', 'llll'),
( 'Sea Witch''s Spell', 'kkkkk', 'llll'),
( 'Sailor''s Delight', 'kkkkk', 'llll'),
( 'Pearl Diving', 'kkkkk', 'llll'),
( 'Neon Nights', 'kkkkk', 'llll'),
( 'Midnight Drive', 'kkkkk', 'llll'),
( 'Jukebox Hero', 'kkkkk', 'llll'),
( 'Backstage Pass', 'kkkkk', 'llll'),
( 'Guitar Solo', 'kkkkk', 'llll'),
( 'Leather and Lace', 'kkkkk', 'llll'),
( 'Stadium Rocker', 'kkkkk', 'llll'),
( 'Fresh Start', 'kkkkk', 'llll'),
( 'First Steps', 'kkkkk', 'llll'),
( 'Blank Canvas', 'kkkkk', 'llll'),
( 'Untitled', 'kkkkk', 'llll'),
( 'Origin Story', 'kkkkk', 'llll'),
( 'Debut', 'kkkkk', 'llll');


album 


INSERT INTO albums (name, songs_list) VALUES
('Hybrid Theory', '1,3,4'),
('Meteora', '2,5,6'),
('Minutes to Midnight', '7,8'),
('Aegean Dreams', '9,10,11,12'),

('Island Melodies', '13,14,16'),

('Backwoods Tales', '15,17,19,20'),


('Neon Nights', '18'),


('Mountain Home', '21,22,23,26,24'),

('Morning in Montmartre', '25'),
('River Romance', '26'),
('Steel and Stone', '27'),
('Boulevard Beats', '28'),
('Art and Soul', '29'),
('Gothic Echoes', '30'),
('Sapphire Seas', '31'),
('Velvet Moon', '32'),
('Cosmic Symphony', '33'),
('Celestial Journey', '34'),
('Heavenly Harmonies', '35'),
('Enchanted Woods', '36'),
('Whimsical Wonders', '37'),
('Prism of Hope', '38'),
('Texas Skies', '39'),
('Bucking Broncos', '40'),
('Remember When', '41'),
('Saltwater Dreams', '42'),
('Natural State', '43'),
('City Slicker', '44'),
('Bluebonnet Fields', '45'),
('Wide Open Spaces', '46'),
('Border Town Beat', '47'),
('Coastal Serenity', '48'),
('Tidal Treasures', '49'),
('Beach Memories', '50'),
('Golden Hour', '51'),
('Marine Melodies', '52'),
('Island Intensity', '53'),
('Underwater Wonders', '54'),
('Mythical Seas', '55'),
('Coastal Contemplations', '56'),
('Bioluminescent Ballet', '57'),
('Aquarium Dreams', '58'),
('Green Depths', '59'),
('Tentacle Tango', '60'),
('Sunken Treasures', '61'),
('Spanish Passion', '62'),
('Wanderlust', '63'),
('Midnight in Buenos Aires', '64'),
('Caribbean Heat', '65'),
('Rio Rhythms', '66'),
('Ipanema Dreams', '67'),
('Havana Nights', '68'),
('Emerald Mists', '69'),
('Ancient Stones', '70'),
('Enchanted Forest', '71'),
('Misty Mountains', '72'),
('Ocean''s Call', '73'),
('Wheel of the Year', '74'),
('Mystic Isle', '75'),
('Folklore and Fantasy', '76'),
('Green Magic', '77'),
('Sahara Nights', '78'),
('Palm and Sand', '79'),
('Silk Road Journey', '80'),
('Heat Haze', '81'),
('Nomad''s Tale', '82'),
('Nature''s Fury', '83'),
('Ancient Mystery', '84'),
('Under the Sea', '85'),
('Underwater Kingdom', '86'),
('Enchanted Waters', '87'),
('Ocean Depths', '88'),
('Dark Tides', '89'),
('Above the Waves', '90'),
('Hidden Treasures', '91'),
('City Lights', '92'),
('Open Road', '93'),
('Rock ''n'' Roll Dreams', '94'),
('Superstar', '95'),
('Six String Stories', '96'),
('Bad Boy Blues', '97'),
('Crowd Pleaser', '98'),
('Beginnings', '99'),
('New Horizons', '100'),
('Infinite Possibilities', '101'),
('Work in Progress', '102'),
('Chapter One', '103'),
('Breaking Through', '104');