
INSERT INTO "songs" VALUES (1,'In the End','kkkkk','llll');
INSERT INTO "songs" VALUES (2,'Numb','kkkkk','llll');
INSERT INTO "songs" VALUES (3,'Crawling','kkkkk','llll');
INSERT INTO "songs" VALUES (4,'One Step Closer','kkkkk','llll');
INSERT INTO "songs" VALUES (5,'Breaking the Habit','kkkkk','llll');
INSERT INTO "songs" VALUES (6,'Faint','kkkkk','llll');
INSERT INTO "songs" VALUES (7,'Bleed It Out','kkkkk','llll');
INSERT INTO "songs" VALUES (8,'What I''ve Done','kkkkk','llll');
INSERT INTO "songs" VALUES (9,'Mediterranean Nights','kkkkk','llll');
INSERT INTO "songs" VALUES (10,'Santorini Sunset','kkkkk','llll');
INSERT INTO "songs" VALUES (11,'Olive Grove Dance','kkkkk','llll');
INSERT INTO "songs" VALUES (12,'Zorba''s Fire','kkkkk','llll');
INSERT INTO "songs" VALUES (13,'Mykonos Breeze','kkkkk','llll');
INSERT INTO "songs" VALUES (14,'Athens by Moonlight','kkkkk','llll');
INSERT INTO "songs" VALUES (15,'Dusty Roads','kkkkk','llll');
INSERT INTO "songs" VALUES (16,'Whiskey River','kkkkk','llll');
INSERT INTO "songs" VALUES (17,'Pickup Truck Blues','kkkkk','llll');
INSERT INTO "songs" VALUES (18,'Honky Tonk Heaven','kkkkk','llll');
INSERT INTO "songs" VALUES (19,'Cowboy''s Lament','kkkkk','llll');
INSERT INTO "songs" VALUES (20,'Heartbreak Highway','kkkkk','llll');
INSERT INTO "songs" VALUES (21,'Bluegrass Memories','kkkkk','llll');
INSERT INTO "songs" VALUES (22,'Smoky Mountain Rain','kkkkk','llll');
INSERT INTO "songs" VALUES (23,'Banjo Breakdown','kkkkk','llll');
INSERT INTO "songs" VALUES (24,'Parisian Nights','kkkkk','llll');
INSERT INTO "songs" VALUES (25,'Cafe au Lait','kkkkk','llll');
INSERT INTO "songs" VALUES (26,'Seine Serenade','kkkkk','llll');
INSERT INTO "songs" VALUES (27,'Eiffel Tower Dreams','kkkkk','llll');
INSERT INTO "songs" VALUES (28,'Champs-Élysées Stroll','kkkkk','llll');
INSERT INTO "songs" VALUES (29,'Louvre''s Mystery','kkkkk','llll');
INSERT INTO "songs" VALUES (30,'Notre-Dame Bells','kkkkk','llll');
INSERT INTO "songs" VALUES (31,'Crystal Waters','kkkkk','llll');
INSERT INTO "songs" VALUES (32,'Midnight Whispers','kkkkk','llll');
INSERT INTO "songs" VALUES (33,'Starlight Sonata','kkkkk','llll');
INSERT INTO "songs" VALUES (34,'Ethereal Dreams','kkkkk','llll');
INSERT INTO "songs" VALUES (35,'Angel''s Lullaby','kkkkk','llll');
INSERT INTO "songs" VALUES (36,'Mystic Forest','kkkkk','llll');
INSERT INTO "songs" VALUES (37,'Fairy Dance','kkkkk','llll');
INSERT INTO "songs" VALUES (38,'Rainbow''s End','kkkkk','llll');
INSERT INTO "songs" VALUES (39,'Lone Star Nights','kkkkk','llll');
INSERT INTO "songs" VALUES (40,'Rodeo Romance','kkkkk','llll');
INSERT INTO "songs" VALUES (41,'Alamo Sunset','kkkkk','llll');
INSERT INTO "songs" VALUES (42,'Gulf Coast Blues','kkkkk','llll');
INSERT INTO "songs" VALUES (43,'Hill Country Rain','kkkkk','llll');
INSERT INTO "songs" VALUES (44,'Big D Lights','kkkkk','llll');
INSERT INTO "songs" VALUES (45,'Yellow Rose','kkkkk','llll');
INSERT INTO "songs" VALUES (46,'Panhandle Wind','kkkkk','llll');
INSERT INTO "songs" VALUES (47,'Rio Grande Rhythm','kkkkk','llll');
INSERT INTO "songs" VALUES (48,'Ocean Breeze','kkkkk','llll');
INSERT INTO "songs" VALUES (49,'Seashell Whispers','kkkkk','llll');
INSERT INTO "songs" VALUES (50,'Sandcastle Dreams','kkkkk','llll');
INSERT INTO "songs" VALUES (51,'Sunset Serenade','kkkkk','llll');
INSERT INTO "songs" VALUES (52,'Dolphin Dance','kkkkk','llll');
INSERT INTO "songs" VALUES (53,'Tropical Storm','kkkkk','llll');
INSERT INTO "songs" VALUES (54,'Coral Reef Symphony','kkkkk','llll');
INSERT INTO "songs" VALUES (55,'Mermaid''s Song','kkkkk','llll');
INSERT INTO "songs" VALUES (56,'Tidal Pool Reflections','kkkkk','llll');
INSERT INTO "songs" VALUES (57,'Jellyfish Waltz','kkkkk','llll');
INSERT INTO "songs" VALUES (58,'Seahorse Lullaby','kkkkk','llll');
INSERT INTO "songs" VALUES (59,'Kelp Forest Whispers','kkkkk','llll');
INSERT INTO "songs" VALUES (60,'Octopus Garden','kkkkk','llll');
INSERT INTO "songs" VALUES (61,'Shipwreck Secrets','kkkkk','llll');
INSERT INTO "songs" VALUES (62,'Flamenco Fire','kkkkk','llll');
INSERT INTO "songs" VALUES (63,'Gypsy Caravan','kkkkk','llll');
INSERT INTO "songs" VALUES (64,'Tango for Two','kkkkk','llll');
INSERT INTO "songs" VALUES (65,'Salsa Nights','kkkkk','llll');
INSERT INTO "songs" VALUES (66,'Samba Sunrise','kkkkk','llll');
INSERT INTO "songs" VALUES (67,'Bossa Nova Breeze','kkkkk','llll');
INSERT INTO "songs" VALUES (68,'Rumba Romance','kkkkk','llll');
INSERT INTO "songs" VALUES (69,'Celtic Twilight','kkkkk','llll');
INSERT INTO "songs" VALUES (70,'Druid''s Dance','kkkkk','llll');
INSERT INTO "songs" VALUES (71,'Fairy Ring','kkkkk','llll');
INSERT INTO "songs" VALUES (72,'Highlands Pipe','kkkkk','llll');
INSERT INTO "songs" VALUES (73,'Selkie''s Song','kkkkk','llll');
INSERT INTO "songs" VALUES (74,'Beltane Fire','kkkkk','llll');
INSERT INTO "songs" VALUES (75,'Avalon''s Dream','kkkkk','llll');
INSERT INTO "songs" VALUES (76,'Wishing Well','kkkkk','llll');
INSERT INTO "songs" VALUES (77,'Leprechaun''s Jig','kkkkk','llll');
INSERT INTO "songs" VALUES (78,'Desert Wind','kkkkk','llll');
INSERT INTO "songs" VALUES (79,'Oasis Dreams','kkkkk','llll');
INSERT INTO "songs" VALUES (80,'Camel Caravan','kkkkk','llll');
INSERT INTO "songs" VALUES (81,'Mirage Melody','kkkkk','llll');
INSERT INTO "songs" VALUES (82,'Bedouin Camp','kkkkk','llll');
INSERT INTO "songs" VALUES (83,'Sandstorm','kkkkk','llll');
INSERT INTO "songs" VALUES (84,'Pyramid''s Secret','kkkkk','llll');
INSERT INTO "songs" VALUES (85,'Mermaid''s Lament','kkkkk','llll');
INSERT INTO "songs" VALUES (86,'Coral Castle','kkkkk','llll');
INSERT INTO "songs" VALUES (87,'Siren''s Call','kkkkk','llll');
INSERT INTO "songs" VALUES (88,'Triton''s Trumpet','kkkkk','llll');
INSERT INTO "songs" VALUES (89,'Sea Witch''s Spell','kkkkk','llll');
INSERT INTO "songs" VALUES (90,'Sailor''s Delight','kkkkk','llll');
INSERT INTO "songs" VALUES (91,'Pearl Diving','kkkkk','llll');
INSERT INTO "songs" VALUES (92,'Neon Nights','kkkkk','llll');
INSERT INTO "songs" VALUES (93,'Midnight Drive','kkkkk','llll');
INSERT INTO "songs" VALUES (94,'Jukebox Hero','kkkkk','llll');
INSERT INTO "songs" VALUES (95,'Backstage Pass','kkkkk','llll');
INSERT INTO "songs" VALUES (96,'Guitar Solo','kkkkk','llll');
INSERT INTO "songs" VALUES (97,'Leather and Lace','kkkkk','llll');
INSERT INTO "songs" VALUES (98,'Stadium Rocker','kkkkk','llll');
INSERT INTO "songs" VALUES (99,'Fresh Start','kkkkk','llll');
INSERT INTO "songs" VALUES (100,'First Steps','kkkkk','llll');
INSERT INTO "songs" VALUES (101,'Blank Canvas','kkkkk','llll');
INSERT INTO "songs" VALUES (102,'Untitled','kkkkk','llll');
INSERT INTO "songs" VALUES (103,'Origin Story','kkkkk','llll');
INSERT INTO "songs" VALUES (104,'Debut','kkkkk','llll');
INSERT INTO "users" VALUES (1,'saran','saran@gmail.com','12345','commom');
INSERT INTO "users" VALUES (2,'linkinpark','lp@song.com','12345','artist');
INSERT INTO "users" VALUES (3,'Yorgo','ygridley0@dagondesign.com','56','artist');
INSERT INTO "users" VALUES (4,'Tedra','tdiegan1@i2i.jp','43','commoner');
INSERT INTO "users" VALUES (5,'Zeke','ztheyer2@istockphoto.com','7593','artist');
INSERT INTO "users" VALUES (6,'Bastien','bandrioni3@acquirethisname.com','307','artist');
INSERT INTO "users" VALUES (7,'Peirce','pkitchen4@buzzfeed.com','20807','commoner');
INSERT INTO "users" VALUES (8,'Chryste','cdykas5@so-net.ne.jp','1','artist');
INSERT INTO "users" VALUES (9,'Dallas','dlebretondelavieuville6@so-net.ne.jp','16248','artist');
INSERT INTO "users" VALUES (10,'Janeen','jreignould7@elegantthemes.com','3','commoner');
INSERT INTO "users" VALUES (11,'Lurette','lwetherburn8@tumblr.com','240','commoner');
INSERT INTO "users" VALUES (12,'Julian','jbeglin9@theglobeandmail.com','2862','commoner');
INSERT INTO "users" VALUES (13,'Salome','struswella@people.com.cn','103','commoner');
INSERT INTO "users" VALUES (14,'Shellie','scranfieldb@sun.com','87847','artist');
INSERT INTO "users" VALUES (15,'Bobbie','bchapec@tumblr.com','871','commoner');
INSERT INTO "users" VALUES (16,'Halimeda','hpaoluccid@homestead.com','3802','artist');
INSERT INTO "users" VALUES (17,'Magnum','mtixiere@prnewswire.com','75954','commoner');
INSERT INTO "users" VALUES (18,'Rossy','rkeanef@people.com.cn','5931','artist');
INSERT INTO "users" VALUES (19,'Olwen','osimakovg@bravesites.com','39','artist');
INSERT INTO "users" VALUES (20,'Udall','uhammanth@usgs.gov','2747','artist');
INSERT INTO "users" VALUES (21,'Ariel','aondrusi@youku.com','85','artist');
INSERT INTO "users" VALUES (22,'Darrell','drubesj@pagesperso-orange.fr','7','artist');
INSERT INTO "users" VALUES (23,'newuser','newusr@eml.com','123456789','artist');
INSERT INTO "users" VALUES (24,'user2','newusr2@eml.com','1234','commom');
INSERT INTO "users" VALUES (25,'user4','usr4@eml.com','1234','commoner');
INSERT INTO "users" VALUES (26,'kwqefjkwq','segk.mwrk@eml.com','12345','commoner');
COMMIT;
